name: zomatodummyapp
description: Zomato Dummy App


version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  adobe_xd: ^0.1.4
  geolocator: ^5.3.2

  http: ^0.12.1
  rxdart: ^0.22.0


dev_dependencies:
  flutter_test:
    sdk: flutter




flutter:



  uses-material-design: true
